import { TimelineEntry } from '../types/TimelineEntry';

export const timelineData: TimelineEntry[] = [
    {
        endYear: 'Present',
        startYear: 2022,
        organisation: 'Modaramo Media',
        title: 'Full-stack Developer',
        location: 'Port Washington, New York, United States',
        details: 'Remote',
        remote: true,
        imgSrc: 'modaramo.png',
    },
    {
        endYear: 2022,
        startYear: 2021,
        organisation: 'Bilge Adam Technologies',
        title: 'Full-stack Developer',
        location: 'Sariyer, Istanbul, Turkey',
        details: 'Remote',
        remote: true,
        imgSrc: 'bilgeadam.png',
    },
    {
        endYear: 2021,
        startYear: 2020,
        organisation: 'Ericsson',
        title: 'Back-end & CRM Developer',
        location: 'Sariyer, Istanbul, Turkey',
        details: 'Remote',
        remote: true,
        imgSrc: 'ericsson.png',
    },
    {
        endYear: 2020,
        startYear: 2019,
        organisation: 'Caretta',
        title: 'Back-end Developer',
        location: 'Sisli, Istanbul, Turkey',
        details: 'On-site',
        remote: false,
        imgSrc: 'caretta.png',
    },
    {
        endYear: 2019,
        startYear: 2018,
        organisation: `L'Oréal`,
        title: 'CRM Developer',
        location: 'Umraniye, Istanbul, Turkey',
        details: 'Outsourced, On-site',
        remote: false,
        imgSrc: 'loreal.png',
    },
    {
        endYear: 2018,
        startYear: 2018,
        organisation: 'Caretta',
        title: 'Assistant Software Engineer',
        location: 'Sisli, Istanbul, Turkey',
        details: 'On-site',
        remote: false,
        imgSrc: 'caretta.png',
    },
    {
        endYear: 2018,
        startYear: 2013,
        organisation: 'Yildiz Technical University',
        title: `Bachelor's Degree in Mathematical Engineering`,
        location: 'Istanbul, Turkey',
        imgSrc: 'ytu.png',
    },
    {
        endYear: 2016,
        startYear: 2016,
        organisation: 'Technological University of the Shannon',
        title: 'Computer Engineering Student',
        location: 'Athlone, Westmeath, Ireland',
        imgSrc: 'tus.png',
    },
];
