import { Experience } from 'App/types/Experience';

export const Experiences: Experience[] = [
    {
        endDate: 'Present',
        startDate: '11-2022',
        organisation: 'Modaramo Media',
        title: 'Full-stack Developer',
        location: 'Port Washington, New York, United States',
        details: 'Remote',
        remote: true,
        imgSrc: 'modaramo.png',
        descriptions: [
            `Contribute to the development of a social media
            application as part of the frontend team and participate
            in mobile development processes using React Native.`,
            `Independently develop a fully functional advertising placement application for the company, focusing on frontend development.`,
            `Support various internal projects, offering both frontend and backend solutions.`,
            `Take full responsibility for the backend development of the "Chatbot" project, utilizing C#.NET and MSSQL to create scalable and robust architectures.`,
            ` Work with technologies such as React, TypeScript, React Native, C#.NET, and MSSQL to deliver high-quality software solutions.`,
        ],
        skills: [
            'react',
            'typescript',
            'javascript',
            'nextjs',
            'csharp',
            'dotnetcore',
            'aspdotnetcore',
            'tsql',
            'mssql',
            'docker',
            'redis',
            'signalr',
            'restsharp',
            'openiddict',
            'serilog',
            'automapper',
            'swagger',
            'efcore',
            'linq',
            'scss',
            'html',
            'css',
            'antd',
            'emotion',
            'styled',
            'chartjs',
            'recharts',
            'i18n',
        ],
    },
    {
        endDate: '11-2022',
        startDate: '09-2021',
        organisation: 'Bilge Adam Technologies',
        title: 'Full-stack Developer',
        location: 'Sariyer, Istanbul, Turkey',
        details: 'Remote',
        remote: true,
        imgSrc: 'bilgeadam.png',
        descriptions: [
            `Contributed to the development and maintenance of a web application used by a large customer base.`,
            `Designed and implemented new modules and algorithms to address complex business logic.`,
            `Worked on a full-stack web application built with ASP.NET Core and React JS, collaborating with an agile team of 7 members.`,
            `Led and managed a team of 2 junior engineers to develop an admin panel for managing on-premise applications, employing Agile methodologies.`,
            `Conducted research on Microservice Architecture to transition monolithic projects and prepare for future company initiatives.`,
        ],
        skills: [
            'dotnetcore',
            'aspdotnetcore',
            'csharp',
            'efcore',
            'linq',
            'docker',
            'rabbitmq',
            'automapper',
            'serilog',
            'redis',
            'mediatr',
            'swagger',
            'react',
            'typescript',
            'javascript',
            'jquery',
            'bootstrap',
            'html',
            'css',
        ],
    },
    {
        endDate: '09-2021',
        startDate: '01-2021',
        organisation: 'Ericsson',
        title: 'Back-end & CRM Developer',
        location: 'Sariyer, Istanbul, Turkey',
        details: 'Remote',
        remote: true,
        imgSrc: 'ericsson.png',
        descriptions: [
            `Developed features for a Dynamics 365 application supporting CRM processes for telecommunications products.`,
            `Designed and implemented REST APIs using .NET, ensuring seamless integration with the Dynamics 365 platform.`,
        ],
        skills: [
            'dotnetcore',
            'aspdotnetcore',
            'csharp',
            'tsql',
            'mssql',
            'crm',
            'swagger',
            'automapper',
        ],
    },
    {
        startDate: '08-2018',
        endDate: '12-2020',
        organisation: 'Caretta',
        title: 'Back-end Developer',
        location: 'Sisli, Istanbul, Turkey',
        details: 'On-site',
        remote: false,
        imgSrc: 'caretta.png',
        descriptions: [
            `Participated in the development and maintenance of 5 web applications built using ASP.NET, working within an agile team comprising a project manager and 5 software developers.`,
            `Created and optimized stored procedures in Microsoft SQL Server to manage and implement business logic efficiently.`,
            `Maintained ETL processes for web applications, executed via a Windows Service, ensuring smooth data integration and processing.`,
            `Contributed to the entire software development life cycle of a web application designed for a client, including attending customer meetings to gather and document project requirements.`,
        ],
        skills: [
            'dotnet',
            'aspdotnet',
            'csharp',
            'mssql',
            'tsql',
            'ef',
            'dapper',
            'javascript',
            'jquery',
            'bootstrap',
            'html',
            'css',
        ],
    },
    {
        startDate: '12-2018',
        endDate: '09-2019',
        organisation: `L'Oréal`,
        title: 'CRM Developer',
        location: 'Umraniye, Istanbul, Turkey',
        details: 'Outsourced, On-site',
        remote: false,
        imgSrc: 'loreal.png',
        descriptions: [
            `Supported for development and maintenance processes of L’Oréal Turkey’s internal projects built on Dynamics CRM.`,
            `Developed C# plugins for projects.`,
            `Made system designing, form customizations, solution management, custom page integrations and workflow development on Dynamics CRM.`,
        ],
        skills: ['crm', 'csharp'],
    },
    {
        startDate: '02-2018',
        endDate: '12-2018',
        organisation: 'Caretta',
        title: 'Assistant Software Engineer',
        location: 'Sisli, Istanbul, Turkey',
        details: 'On-site',
        remote: false,
        imgSrc: 'caretta.png',
        descriptions: [
            `Worked alongside by a developer to develop some modules on a web application build on ASP.NET.`,
            `Some modules are developed for an in-house web application from scratch and these modules were used by employees.`,
        ],
        skills: ['crm', 'csharp'],
    },
    {
        endDate: '02-2018',
        startDate: '09-2013',
        organisation: 'Yildiz Technical University',
        title: `Bachelor's Degree in Mathematical Engineering`,
        location: 'Istanbul, Turkey',
        imgSrc: 'ytu.png',
        skills: [],
    },
    {
        endDate: '12-2016',
        startDate: '09-2016',
        organisation: 'Technological University of the Shannon',
        title: 'Computer Engineering Student',
        location: 'Athlone, Westmeath, Ireland',
        imgSrc: 'tus.png',
        skills: [],
    },
];
