import { Experience } from 'App/types/Experience';

export const Experiences: Experience[] = [
    {
        endDate: 'Present',
        startDate: '11-2022',
        organisation: 'Modaramo Media',
        title: 'Full-stack Developer',
        location: 'Port Washington, New York, United States',
        details: 'Remote',
        remote: true,
        imgSrc: 'modaramo.png',
        descriptions: [
            `Led the backend development of an enterprise grade chatbot platform, architected with C#.NET and MS SQL Server, integrating OpenAI’s ChatGPT API to enable AI powered conversations for 50K+ users.`,
            `Built both the backend (.NET Core) and frontend components (React dashboard & widget) for the chatbot application, resulting in a 40% faster socket response and an optimized, scalable architecture.`,
            `Contributed to a social media platform, implementing key frontend features and collaborating with designers and backend teams to ship 3 major feature releases per quarter.`,
            `Designed and built a full ad placement platform, taking full ownership of all frontend processes and delivering a tool that managed 200+ ad campaigns per month.`,
            `Provided full stack solutions for multiple internal products, ensuring seamless communication between frontend components and backend services.`,
            `Leveraged a diverse technology stack (React, TypeScript, C#.NET, MS SQL Server, MySQL) to deliver scalable, maintainable, and high performance applications.`,
        ],
        skills: [
            'react',
            'typescript',
            'javascript',
            'nextjs',
            'csharp',
            'dotnetcore',
            'aspdotnetcore',
            'tsql',
            'mssql',
            'docker',
            'redis',
            'signalr',
            'restsharp',
            'openiddict',
            'serilog',
            'automapper',
            'swagger',
            'efcore',
            'linq',
            'scss',
            'html',
            'css',
            'antd',
            'emotion',
            'styled',
            'chartjs',
            'recharts',
            'i18n',
        ],
    },
    {
        endDate: '11-2022',
        startDate: '09-2021',
        organisation: 'Bilge Adam Technologies',
        title: 'Full-stack Developer',
        location: 'Sariyer, Istanbul, Turkey',
        details: 'Remote',
        remote: true,
        imgSrc: 'bilgeadam.png',
        descriptions: [
            `Contributed to the development of a Human Resources platform, streamlining performance tracking, leave management, and employee data processing for internal HR teams serving 1,000+ employees.`,
            `Implemented CV parsing features that extracted structured data from LinkedIn and Kariyer.net profiles, creating a centralized talent pool that accelerated candidate screening.`,
            `Transformed frontend modules for a major bank’s applicant portal, increasing online submissions by ~30% and improving user experience.`,
            `Designed and implemented new modules and algorithms to support complex HR workflows, reducing manual processing efforts by ~25%.`,
            `Led and mentored 2 junior engineers to develop a custom admin panel for managing on premise deployments, ensuring compliance with Agile best practices.`,
            `Conducted research and provided recommendations for migrating legacy monolith systems to microservices architecture, laying the foundation for a scalable and modular ecosystem.`,
        ],
        skills: [
            'dotnetcore',
            'aspdotnetcore',
            'csharp',
            'efcore',
            'linq',
            'docker',
            'rabbitmq',
            'automapper',
            'serilog',
            'redis',
            'mediatr',
            'swagger',
            'react',
            'typescript',
            'javascript',
            'jquery',
            'bootstrap',
            'html',
            'css',
        ],
    },
    {
        endDate: '09-2021',
        startDate: '01-2021',
        organisation: 'Ericsson',
        title: 'Back-end & CRM Developer',
        location: 'Sariyer, Istanbul, Turkey',
        details: 'Remote',
        remote: true,
        imgSrc: 'ericsson.png',
        descriptions: [
            `Contributed to Dynamics 365 CRM customization and .NET integrations for telecom-related processes.`,
        ],
        skills: [
            'dotnetcore',
            'aspdotnetcore',
            'csharp',
            'tsql',
            'mssql',
            'crm',
            'swagger',
            'automapper',
        ],
    },
    {
        startDate: '08-2018',
        endDate: '12-2020',
        organisation: 'Caretta',
        title: 'Back-end Developer',
        location: 'Sisli, Istanbul, Turkey',
        details: 'On-site',
        remote: false,
        imgSrc: 'caretta.png',
        descriptions: [
            `Contributed to the development and maintenance of 5+ enterprise web applications for global pharmaceutical clients (Bayer, Pfizer, Sanofi and others), enhancing user engagement and streamlining operations for thousands of end users.`,
            `Coordinated efforts within an agile team of 5 developers and 1 PM, contributing to the delivery of 4 major end to end systems that streamlined production, sales, and logistics management for multiple pharmaceutical clients.`,
            `Engineered and optimized complex stored procedures in MS SQL Server, improving query performance by 35% and ensuring consistent, reliable business logic for mission critical systems.`,
            `Oversaw and optimized ETL processes running on Windows Services, ensuring accurate transfer of millions of data records per day between internal and external systems and reducing processing errors by 15%.`,
            `Collaborated with stakeholders to analyze and synthesize requirements, ensuring 100% compliance with pharmaceutical regulations and streamlining approval workflows for critical systems.
`,
        ],
        skills: [
            'dotnet',
            'aspdotnet',
            'csharp',
            'mssql',
            'tsql',
            'ef',
            'dapper',
            'javascript',
            'jquery',
            'bootstrap',
            'html',
            'css',
        ],
    },
    {
        startDate: '12-2018',
        endDate: '09-2019',
        organisation: `L'Oréal`,
        title: 'CRM Developer',
        location: 'Umraniye, Istanbul, Turkey',
        details: 'Outsourced, On-site',
        remote: false,
        imgSrc: 'loreal.png',
        descriptions: [
            `Supported for development and maintenance processes of L’Oréal Turkey’s internal projects built on Dynamics CRM.`,
            `Developed C# plugins for projects.`,
            `Made system designing, form customizations, solution management, custom page integrations and workflow development on Dynamics CRM.`,
        ],
        skills: ['crm', 'csharp'],
    },
    {
        startDate: '02-2018',
        endDate: '12-2018',
        organisation: 'Caretta',
        title: 'Assistant Software Engineer',
        location: 'Sisli, Istanbul, Turkey',
        details: 'On-site',
        remote: false,
        imgSrc: 'caretta.png',
        descriptions: [],
        skills: ['crm', 'csharp'],
    },
    {
        endDate: '02-2018',
        startDate: '09-2013',
        organisation: 'Yildiz Technical University',
        title: `Bachelor's Degree in Mathematical Engineering`,
        location: 'Istanbul, Turkey',
        imgSrc: 'ytu.png',
        skills: [],
    },
    {
        endDate: '12-2016',
        startDate: '09-2016',
        organisation: 'Technological University of the Shannon',
        title: 'Computer Engineering Student',
        location: 'Athlone, Westmeath, Ireland',
        imgSrc: 'tus.png',
        skills: [],
    },
];
