import { Skill } from 'App/types/Skill';
import {
    AntdIcon,
    BootstrapIcon,
    ChartjsIcon,
    CssIcon,
    EmotionIcon,
    HtmlIcon,
    JavascriptIcon,
    JQueryIcon,
    NextIcon,
    ReactIcon,
    ReduxIcon,
    ScssIcon,
    StyledComponentsIcon,
    TypescriptIcon,
    I18NextIcon,
    MotionIcon,
    CSharpIcon,
    TSQLIcon,
    DotNetCoreIcon,
    MongoDbIcon,
    RedisIcon,
    BitbucketIcon,
    GithubIcon,
    JiraIcon,
    FigmaIcon,
    PhotoshopIcon,
    SlackIcon,
    TeamsIcon,
    PostmanIcon,
    VisualStudioIcon,
    VisualStudioCodeIcon,
    DynamicsCrmIcon,
    ChatgptIcon,
    DockerIcon,
    DotNetIcon,
    AzureDevOpsIcon,
    RabbitMQIcon,
    SwaggerIcon,
    SignalRIcon,
    OpenIddictIcon,
    AutoMapperIcon,
} from 'Core/components/Icons';
import RechartsIcon from 'Core/components/Icons/recharts';
import { SkillType } from 'App/types/SkillType';

export const SkillSet: Record<SkillType, Skill> = {
    typescript: {
        name: 'Typescript',
        area: 'frontend',
        category: 'language',
        color: '#3178c6',
        icon: <TypescriptIcon />,
    },
    javascript: {
        name: 'Javascript',
        area: 'frontend',
        category: 'language',
        color: '#ebd100',
        icon: <JavascriptIcon />,
    },
    html: {
        name: 'HTML',
        area: 'frontend',
        category: 'language',
        color: '#e34e25',
        icon: <HtmlIcon />,
    },
    css: {
        name: 'CSS',
        area: 'frontend',
        category: 'language',
        color: '#264de4',
        icon: <CssIcon />,
    },
    scss: {
        name: 'SCSS',
        area: 'frontend',
        category: 'library',
        color: '#cd5392',
        icon: <ScssIcon />,
    },
    react: {
        name: 'React',
        area: 'frontend',
        category: 'framework',
        color: '#61dafb',
        icon: <ReactIcon />,
    },
    nextjs: {
        name: 'Next.js',
        area: 'frontend',
        category: 'framework',
        color: '#000000',
        icon: <NextIcon />,
    },
    antd: {
        name: 'Ant Design',
        area: 'frontend',
        category: 'library',
        color: '#0e70fe',
        icon: <AntdIcon />,
    },
    bootstrap: {
        name: 'Bootstrap',
        area: 'frontend',
        category: 'library',
        color: '#7c12f8',
        icon: <BootstrapIcon />,
    },
    emotion: {
        name: 'Emotion',
        area: 'frontend',
        category: 'library',
        color: '#a45b9c',
        icon: <EmotionIcon />,
    },
    styled: {
        name: 'Styled Components',
        area: 'frontend',
        category: 'library',
        color: '#9a6ac2',
        icon: <StyledComponentsIcon />,
    },
    jquery: {
        name: 'jQuery',
        area: 'frontend',
        category: 'library',
        color: '#0868ac',
        icon: <JQueryIcon />,
    },
    redux: {
        name: 'Redux',
        area: 'frontend',
        category: 'library',
        color: '#7649bb',
        icon: <ReduxIcon />,
    },
    chartjs: {
        name: 'Chart.js',
        area: 'frontend',
        category: 'library',
        color: '#fe777b',
        icon: <ChartjsIcon />,
    },
    recharts: {
        name: 'Recharts',
        area: 'frontend',
        category: 'library',
        color: '#000000',
        icon: <RechartsIcon />,
    },
    i18n: {
        name: 'i18n',
        area: 'frontend',
        category: 'library',
        color: '#009788',
        icon: <I18NextIcon />,
    },
    motion: {
        name: 'Motion',
        area: 'frontend',
        category: 'library',
        color: '#f0e511',
        icon: <MotionIcon />,
    },
    csharp: {
        name: 'C#',
        area: 'backend',
        category: 'language',
        color: '#9a4e95',
        icon: <CSharpIcon />,
    },
    tsql: {
        name: 'T-SQL',
        area: 'backend',
        category: 'language',
        color: '#d9425d',
        icon: <TSQLIcon />,
    },
    dotnetcore: {
        name: '.NET Core',
        area: 'backend',
        category: 'framework',
        color: '#621ee5',
        icon: <DotNetCoreIcon />,
    },
    aspdotnetcore: {
        name: 'ASP.NET Core',
        area: 'backend',
        category: 'framework',
        color: '#621ee5',
        icon: <DotNetCoreIcon />,
    },
    dotnet: {
        name: '.NET Framework',
        area: 'backend',
        category: 'framework',
        color: '#0d6bb1',
        icon: <DotNetIcon />,
    },
    aspdotnet: {
        name: 'ASP.NET',
        area: 'backend',
        category: 'framework',
        color: '#0d6bb1',
        icon: <DotNetIcon />,
    },
    efcore: {
        name: 'Entity Framework Core',
        area: 'backend',
        category: 'orm',
        color: '#671f78',
    },
    ef: {
        name: 'Entity Framework',
        area: 'backend',
        category: 'orm',
        color: '#671f78',
    },
    dapper: {
        name: 'Dapper',
        area: 'backend',
        category: 'orm',
        color: '#671f78',
    },
    linq: {
        name: 'LINQ',
        area: 'backend',
        category: 'orm',
        color: '#671f78',
    },
    mssql: {
        name: 'Microsoft SQL Server',
        area: 'backend',
        category: 'database',
        color: '#d9425d',
        icon: <TSQLIcon />,
    },
    mongodb: {
        name: 'MongoDB',
        area: 'backend',
        category: 'database',
        color: '#17823f',
        icon: <MongoDbIcon />,
    },
    redis: {
        name: 'Redis',
        area: 'backend',
        category: 'database',
        color: '#cb291c',
        icon: <RedisIcon />,
    },
    signalr: {
        name: 'SignalR',
        area: 'backend',
        category: 'tools & libraries',
        color: '#00abec',
        icon: <SignalRIcon />,
    },
    swagger: {
        name: 'Swagger',
        area: 'backend',
        category: 'tools & libraries',
        color: '#49a32b',
        icon: <SwaggerIcon />,
    },
    rabbitmq: {
        name: 'RabbitMQ',
        area: 'backend',
        category: 'tools & libraries',
        color: '#ff6600',
        icon: <RabbitMQIcon />,
    },
    mediatr: {
        name: 'MediatR',
        area: 'backend',
        category: 'tools & libraries',
        color: '#1593c8',
    },
    serilog: {
        name: 'Serilog',
        area: 'backend',
        category: 'tools & libraries',
        color: '#ff2318',
    },
    openiddict: {
        name: 'OpenIddict',
        area: 'backend',
        category: 'tools & libraries',
        color: '#ff6200',
        icon: <OpenIddictIcon />,
    },
    restsharp: {
        name: 'RestSharp',
        area: 'backend',
        category: 'tools & libraries',
        color: '#000066',
    },
    automapper: {
        name: 'AutoMapper',
        area: 'backend',
        category: 'tools & libraries',
        color: '#db1121',
        icon: <AutoMapperIcon />,
    },
    bitbucket: {
        name: 'Bitbucket',
        area: 'tools',
        category: 'default',
        color: '#0659d3',
        icon: <BitbucketIcon />,
    },
    github: {
        name: 'Github',
        area: 'tools',
        category: 'default',
        color: '#000000',
        icon: <GithubIcon />,
    },
    jira: {
        name: 'Jira',
        area: 'tools',
        category: 'default',
        color: '#2684ff',
        icon: <JiraIcon />,
    },
    figma: {
        name: 'Figma',
        area: 'tools',
        category: 'default',
        color: '#a259ff',
        icon: <FigmaIcon />,
    },
    azuredevops: {
        name: 'Azure DevOps Server (TFS)',
        area: 'tools',
        category: 'default',
        color: '#318de2',
        icon: <AzureDevOpsIcon />,
    },
    photoshop: {
        name: 'Photoshop',
        area: 'tools',
        category: 'default',
        color: '#32adff',
        icon: <PhotoshopIcon />,
    },
    slack: {
        name: 'Slack',
        area: 'tools',
        category: 'default',
        color: '#e01e5a',
        icon: <SlackIcon />,
    },
    teams: {
        name: 'Teams',
        area: 'tools',
        category: 'default',
        color: '#424ab4',
        icon: <TeamsIcon />,
    },
    vs: {
        name: 'Visual Studio',
        area: 'tools',
        category: 'default',
        color: '#7252aa',
        icon: <VisualStudioIcon />,
    },
    vscode: {
        name: 'Visual Studio Code',
        area: 'tools',
        category: 'default',
        color: '#007abf',
        icon: <VisualStudioCodeIcon />,
    },
    postman: {
        name: 'Postman',
        area: 'tools',
        category: 'default',
        color: '#ff6016',
        icon: <PostmanIcon />,
    },
    docker: {
        name: 'Docker',
        area: 'tools',
        category: 'default',
        color: '#1794d4',
        icon: <DockerIcon />,
    },
    chatgpt: {
        name: 'ChatGPT',
        area: 'tools',
        category: 'default',
        color: '#74aa9c',
        icon: <ChatgptIcon />,
    },
    crm: {
        name: 'Microsoft Dynamics 365 CRM',
        area: 'tools',
        category: 'default',
        color: '#00255a',
        icon: <DynamicsCrmIcon />,
    },
};
