export type Language = "tr" | "en";

export const copy = {
  tr: {
    language: { label: "Dil", tr: "TR", en: "EN" },
    studio: {
      nav: { games: "Oyunlar", studio: "Stüdyo", journal: "Günlük", contact: "İletişim" },
      heroTagline: "Rüzgârın taşıdığı hikâyeler.",
      manifestoLabel: "HOLLOWGALE MANİFESTOSU",
      manifestoTitle: "Her dünya bir iz bırakır.",
      manifestoAside: "Oyunlar, insanları yeni hikâyelerle buluşturur.",
      gameLabel: "01 / İLK OYUNUMUZ",
      comingSoon: "YAKINDA",
      gameLead: "Konağın kapıları yakında açılıyor.",
      discoverGame: "Oyunu keşfet",
      gameAside: "SIRLAR\nODALAR\nKADERLER\nSİZİ BEKLİYOR.",
      aboutLabel: "02 / STÜDYO",
      aboutTitle: "Küçük bir ekip.\nKendine özgü dünyalar.",
      aboutLead: "Hikâyeyi mekânın içinde hissettiren, merakla keşfedilen oyunlar tasarlıyoruz.",
      values: ["HAYAL GÜCÜ", "MEKÂN", "KEŞİF", "ANLAMLI OYUNLAR"],
      journalLabel: "03 / GELİŞTİRME GÜNLÜĞÜ",
      journalTitle: "Geliştirme\ngünlüğü",
      journalLead: "Oyunlarımızın dünyasından kısa bakışlar, fikirler ve süreçler.",
      allNotes: "Tüm notlar",
      entries: ["Konağın içinden", "Bir odanın hikâyesi", "Koridorun sonunda"],
      ctaTitle: "Yeni bir hikâyeye hazır mısın?",
      cta: "Bizimle konuş",
      footerLine: "Hikâyeler daima bir yol bulur.",
      scroll: "Keşfetmek için kaydır",
    },
    game: {
      nav: { game: "Oyun", mansion: "Konak", gallery: "Galeri" },
      wishlist: "İstek listesine ekle",
      tagline: "Konağın kapıları açılıyor.",
      trailer: "Fragmanı izle",
      secret: "Bazı kapılar asla yalnız değildir.",
      sectionTitle: "Her kapının ardında bir sır.",
      gallery: ["Konağı keşfet", "İpuçlarını takip et", "Sırları ortaya çıkar"],
      stepInside: "Konağa adım at.",
      explore: "Mansion of Fates dünyasını keşfet.",
      seeGallery: "Galeriye bak",
      footerLine: "Kader daima bir yol bulur.",
      backStudio: "Hollowgale Games'e dön",
    },
  },
  en: {
    language: { label: "Language", tr: "TR", en: "EN" },
    studio: {
      nav: { games: "Games", studio: "Studio", journal: "Journal", contact: "Contact" },
      heroTagline: "Stories carried by the wind.",
      manifestoLabel: "THE HOLLOWGALE MANIFESTO",
      manifestoTitle: "Every world leaves a trace.",
      manifestoAside: "Games connect us through stories.",
      gameLabel: "01 / OUR FIRST GAME",
      comingSoon: "COMING SOON",
      gameLead: "The mansion doors will open soon.",
      discoverGame: "Discover the game",
      gameAside: "SECRETS\nROOMS\nFATES\nAWAIT YOU.",
      aboutLabel: "02 / STUDIO",
      aboutTitle: "A small team.\nWorlds of our own.",
      aboutLead: "We create games that let you feel the story in every place and reward curiosity.",
      values: ["IMAGINATION", "PLACE", "DISCOVERY", "MEANINGFUL PLAY"],
      journalLabel: "03 / DEVELOPMENT JOURNAL",
      journalTitle: "Development\njournal",
      journalLead: "Notes, ideas and glimpses from the worlds we are building.",
      allNotes: "All notes",
      entries: ["Inside the mansion", "The story of a room", "At the corridor's end"],
      ctaTitle: "Ready for a new story?",
      cta: "Talk to us",
      footerLine: "Stories always find a way.",
      scroll: "Scroll to explore",
    },
    game: {
      nav: { game: "Game", mansion: "Mansion", gallery: "Gallery" },
      wishlist: "Add to wishlist",
      tagline: "The mansion doors are opening.",
      trailer: "Watch trailer",
      secret: "Some doors are never alone.",
      sectionTitle: "A secret behind every door.",
      gallery: ["Explore the mansion", "Follow the clues", "Reveal its secrets"],
      stepInside: "Step inside the mansion.",
      explore: "Discover the world of Mansion of Fates.",
      seeGallery: "View gallery",
      footerLine: "Fate always finds a way.",
      backStudio: "Back to Hollowgale Games",
    },
  },
} as const;
