export type SkillName =
    | 'Typescript'
    | 'Javascript'
    | 'HTML'
    | 'CSS'
    | 'SCSS'
    | 'React'
    | 'Next.js'
    | 'Ant Design'
    | 'Bootstrap'
    | 'Emotion'
    | 'Styled Components'
    | 'jQuery'
    | 'Redux'
    | 'Chart.js'
    | 'Recharts'
    | 'i18n'
    | 'Motion'
    | 'C#'
    | 'T-SQL'
    | '.NET Core'
    | 'ASP.NET Core'
    | '.NET Framework'
    | 'ASP.NET'
    | 'Entity Framework Core'
    | 'Entity Framework'
    | 'Dapper'
    | 'LINQ'
    | 'Microsoft SQL Server'
    | 'MongoDB'
    | 'Redis'
    | 'Bitbucket'
    | 'Azure DevOps Server (TFS)'
    | 'Github'
    | 'Jira'
    | 'Figma'
    | 'Photoshop'
    | 'Slack'
    | 'Teams'
    | 'Visual Studio'
    | 'Visual Studio Code'
    | 'Postman'
    | 'Docker'
    | 'ChatGPT'
    | 'Microsoft Dynamics 365 CRM'
    | 'SignalR'
    | 'Swagger'
    | 'RabbitMQ'
    | 'MediatR'
    | 'OpenIddict'
    | 'Serilog'
    | 'AutoMapper'
    | 'RestSharp';
